### ISSUE TITLE
Different scale in microarray and rnaseq data

### ISSUE THREAD

**Issue by ben-heil** [greenelab/whistl#1]
I noticed that rnaseq data was getting much larger outputs than microarray data when using untrained models. Upon closer examination, microarray samples had mean expresssions across all genes between zero and one, while rnaseq had values in the tens.

My guess would be that the quantile normalization on the refine.bio side is different for RNAseq and microarray data (which makes sense). I'll have to put some thought into how to properly normalize the data types to bring them all into the same scale.

**Comment by cgreene** [comment]
Can you file this ticket in refine.bio?

**Comment by ben-heil** [comment]
Sure thing, I'll dig deeper into it on Monday to get some more precise numbers and study IDs.

**Comment by ben-heil** [comment]
Turned out to be a refine.bio issue, resolved in issue 1774 referenced above
